n = int(input('Qual número deseja saber a tabuada? '))
print('Sua tabuada é:')
print(f'{n}x1 = {n * 1}')
print(f'{n}x2 = {n * 2}')
print(f'{n}x3 = {n * 3}')
print(f'{n}x4 = {n * 4}')
print(f'{n}x5 = {n * 5}')
print(f'{n}x6 = {n * 6}')
print(f'{n}x7 = {n * 7}')
print(f'{n}x8 = {n * 8}')
print(f'{n}x9 = {n * 9}')
